function explosion(pos,radius,force,coreDamage){for(const b of blocks){if(b.hidden)continue;const d=len(sub(b.pos,pos));if(d<radius){activate(b,add(mul(norm(sub(b.pos,pos)),(radius-d)*force),V(0,(radius-d)*force*.65,0)));if(coreDamage&&d<radius*.55)b.hp--,b.hp<=0&&(b.hidden=true,burst(b.pos,0xaebcff,14,3))}}for(const b of barrels){if(!b.hidden&&len(sub(b.pos,pos))<radius*.9)setTimeout(()=>explodeBarrel(b),80)}for(const c of cores){if(c.alive&&len(sub(c.pos,pos))<radius*.82)damageCore(c,1)}}

function updateProjectiles(dt){for(const p of projectiles){if(!p.alive||p.hidden)continue;p.age+=dt;if(p.age<0){p.hidden=true;continue}else p.hidden=false;p.vel.y-=7.6*dt;p.pos=add(p.pos,mul(p.vel,dt));let hit=false;for(const c of cores){if(c.alive&&len(sub(p.pos,c.pos))<p.radius+(c.shield>0?.55:c.r)){damageCore(c,p.heavy?2:1);p.alive=false;p.hidden=true;hit=true;break}}if(hit)continue;for(const b of barrels){if(b.hidden)continue;if(len(sub(p.pos,b.pos))<p.radius+b.radius){explodeBarrel(b);p.alive=false;p.hidden=true;hit=true;break}}if(hit)continue;for(const b of blocks){if(b.hidden)continue;const h=aabbHit(p,b);if(h){damageBlock(p,b,h);p.pos=add(p.pos,mul(h.n,.05));break}}if(p.pos.y<p.radius){p.pos.y=p.radius;p.vel.y=Math.abs(p.vel.y)*.44;p.vel.x*=.76;p.vel.z*=.76;shake=Math.max(shake,1)}if(p.age>5.8||Math.abs(p.pos.x)>11||p.pos.z<-20||p.pos.z>10){p.alive=false;p.hidden=true}}for(let i=projectiles.length-1;i>=0;i--)if(!projectiles[i].alive)projectiles.splice(i,1)}

function updateBlocks(dt){for(const b of blocks){if(b.hidden||!b.dynamic)continue;b.vel.y-=7.6*dt;b.pos=add(b.pos,mul(b.vel,dt));b.rot.x+=b.ang.x*dt;b.rot.y+=b.ang.y*dt;b.rot.z+=b.ang.z*dt;b.vel=mul(b.vel,Math.pow(.986,dt*60));b.ang=mul(b.ang,Math.pow(.975,dt*60));const floor=b.scale.y*.5+.02;if(b.pos.y<floor){b.pos.y=floor;b.vel.y=Math.abs(b.vel.y)*.18;b.vel.x*=.66;b.vel.z*=.66;b.ang=mul(b.ang,.55);if(len(b.vel)<.32)b.dynamic=false}for(const c of cores)if(c.alive&&len(sub(b.pos,c.pos))<b.radius*.35+.45){damageCore(c,1);b.vel=mul(b.vel,.3)}}for(const b of barrels){if(b.hidden||!b.dynamic)continue;b.vel.y-=7.6*dt;b.pos=add(b.pos,mul(b.vel,dt));if(b.pos.y<.53){b.pos.y=.53;b.vel.y=Math.abs(b.vel.y)*.2;b.vel.x*=.7;b.vel.z*=.7}}}

function updateCannon(){const d=dir(),yaw=aim.yaw,pitch=aim.pitch;for(const p of cannonParts.slice(3)){p.rot.x=-Math.PI/2+pitch;p.rot.z=-yaw;const L=p===cannonParts[3]?1.02:2.08;p.pos=V(d.x*L,.96+d.y*L,5.72+d.z*L)}}

function updateCores(t){for(const c of cores){if(!c.alive)continue;c.phase+=dtGlobal*(c.moving?1.6:.5);if(c.moving)c.pos.x=c.base.x+Math.sin(t*1.25+c.phase)*.72;c.rot.x+=.012;c.rot.y+=.021;const s=1+Math.sin(t*4+c.phase)*.08;c.scale=V(.62*s,.62*s,.62*s);if(c.shieldObj){c.shieldObj.pos=V(c.pos.x,c.pos.y,c.pos.z);c.shieldObj.rot.y-=.01;c.shieldObj.scale=V(1.05+Math.sin(t*3+c.phase)*.05,1.05+Math.sin(t*3+c.phase)*.05,1.05+Math.sin(t*3+c.phase)*.05)}}}
